### ISSUE TITLE
Encouragement

### ISSUE THREAD

**Issue by markab21** [CoffeeBlend/XEcmaScript#1]
Not sure where to put this, saw a link from a random forum on google, but I just wanted to **thank you** for working on this.  Once it's ready there is a project I'd like to use it in.   Keep it up!  Try to at least get to the point where there is a working mvp, you'll gain interest and help fast.  : ) 

I'm an elixir/javascript dev but would be happy to help out once the project gets a little bit further along.  Maybe once you get to the point of adding data-ref's and such I'd be happy to help fill out the blanks or test the plugin with my app once it's closer to being usable.

**Comment by joboet** [comment]
There is already implementation for DataRefs as well as flight loop callbacks. I will make a wiki entry on them soon.
