### ISSUE TITLE
V8

### ISSUE THREAD

**Issue by kbrandwijk** [CoffeeBlend/XEcmaScript#2]
Very interesting project, I am also looking at using JS for X-Plane plugins, so this is a great starting point. Did you consider using the V8 engine instead of SpiderMonkey?

**Comment by joboet** [comment]
Yes, but at the time I started the project, I was having major difficulties getting it to compile. As far as I know the differences in performance between v8 and Spidermonkey are very small. Should there be an obvious reason for switching I will do it, but for the moment I’m happy with Spidermonkey. If you need v8 now, feel free to make a fork and change the corresponding code segments. It should not be too difficult, as the APIs are somewhat similar. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
